name: ci

on:
  push:
    branches:
      - main
      - develop
      - dragon
    tags:
      - "*"
  pull_request:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  WAGO_PROJECT_ID: WqKQw1Nx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"

      - name: Prepare zip file & create a release
        if: github.ref_type == 'tag'
        env:
          CHANGELOG: ${{ github.event.head_commit.message }}
          TAG_NAME: ${{ github.ref_name }}
        run: .github/workflows/release.sh
      - name: Upload to wago.io
        if: github.ref_type == 'tag'
        env:
          CHANGELOG: ${{ github.event.head_commit.message }}
          TAG_NAME: ${{ github.ref_name }}
        run: .github/workflows/upload2wago.sh
